line 31 attempt to compute `((*_1).0: usize) + const 1_usize`, which would overflow: SUCCESS
line 31 arithmetic overflow on unsigned + in self->len + 1: SUCCESS
line 56 assertion: a.is_some(): FAILURE
line 57 assertion: a.is_none(): FAILURE
line 59 assertion: b.is_some(): SUCCESS
line 60 assertion: b.is_none(): FAILURE
